import { Workbook } from 'exceljs';

export const getWorkbookFromJsObj = ({ jsObjArray, workbookOptions } = {}) => {

  const workbook = new Workbook();
  workbook.title = workbookOptions.title || 'Puntos Luz Reporte';
  workbook.company = workbookOptions.company || 'The Data Age, AES El Salvador';
  workbook.creator = workbookOptions.creator || 'The Data Age';
  workbook.created = new Date();
  workbook.description = workbookOptions.description || 'report generated by puntos luz web software';

  const worksheet = workbook.addWorksheet("Rep. pagina 1");

  worksheet.columns = Object.keys(jsObjArray[0]).map((key) => {
    return {
      header: key,
      key: key,
      width: key.length + 8
    }
  });

  worksheet.addRows(jsObjArray);

  return workbook;
}

export const initializeWorkbookFromJsObj = ({ workbookOptions } = {}) => {

  const workbook = new Workbook();
  workbook.title = workbookOptions.title || 'Puntos Luz Reporte';
  workbook.company = workbookOptions.company || 'The Data Age, AES El Salvador';
  workbook.creator = workbookOptions.creator || 'The Data Age';
  workbook.created = new Date();
  workbook.description = workbookOptions.description || 'report generated by puntos luz web software';

  return workbook;
}

export const addWorksheetToWorkbook = ({ workbook, jsObjArray, name } = {}) => {
  const worksheet = workbook.addWorksheet(name);

  worksheet.columns = Object.keys(jsObjArray[0]).map((key) => {
    return {
      header: key,
      key: key,
      width: key.length + 8
    }
  });

  return {workbook, worksheet};
}

export const addJsObjToWorksheet = ({ worksheet, jsObjArray } = {}) => {
  worksheet.addRows(jsObjArray);
}
